export const projects = [
	{
		id: 1,
		title: 'Landscape Friend',
		text: 'A SaaS platform for landscapers and lawn care businesses to manage services, send emails, and invoices.',
		imagePath: '/landscapefriend.png',
		url: 'https://landscapefriend.com',
		githubUrl: 'https://github.com/Pmacdon15/landscape-friend',
	},
	{
		id: 2,
		title: 'CLock Out',
		text: 'A time tracking app with secure authentication, organization management, and visual analytics.',
		imagePath: '/clockout.png',
		githubUrl: 'https://github.com/Pmacdon15/clock-out',
		url: 'https://clockout.patmac.ca',
	},
	{
		id: 3,
		title: 'PolyMuse Wordpress WooCommerce Plugin',
		text: 'A custom plugin for Polymuse, enabling 3D model display and AR views on mobile devices.',
		imagePath: '/polymuse.jpeg',
		githubUrl: 'https://github.com/Dream-Team-Seven/polymuse-woocommerce',
	},
	{
		id: 4,
		title: "Pat's Pre-Trips",
		text: 'A pre-trip inspection app with authentication, current and past trips, and defect listing.',
		imagePath: '/patspretrips1.png',
		githubUrl: 'https://github.com/Pmacdon15/pats-pretrips',
		url: 'https://patspretrips.ca/',
	},
	{
		id: 5,
		title: "Pat's Blogs",
		text: 'A modern blog site with image, code, and text upload, and Neon database storage.',
		imagePath: '/blogs.png',
		githubUrl: 'https://github.com/Pmacdon15/blog',
		url: 'https://blog.patmac.ca/',
	},
	{
		id: 6,
		title: 'Pat GPT',
		text: 'An Android chat and image generator app using GPT-3 Turbo and DALL-E-3 models.',
		imagePath: '/PatGPT.png',
		githubUrl: 'https://github.com/Pmacdon15/PatGPT',
	},
	{
		id: 7,
		title: 'Free QR Code Generator',
		text: 'A modern QR code generator with URL formatting and PNG download.',
		imagePath: '/qrcode.png',
		githubUrl: 'https://github.com/Pmacdon15/free-qrcode',
		url: 'https://freeqrcode.patmac.ca/',
	},
	{
		id: 8,
		title: 'Pat Chat 2.0',
		text: 'A real-time chat application built with TypeScript, Next.js, and Ably.',
		imagePath: '/PatChat2.png',
		githubUrl: 'https://github.com/Pmacdon15/patchat2.0',
		url: 'https://www.patchat.ca',
	},
	{
		id: 10,
		title: 'Guess The Celebrity Game',
		text: 'An Android game developed in Java, focusing on saving and restoring state.',
		imagePath: '/GuessingGame.png',
		githubUrl: 'https://github.com/Pmacdon15/Guess-The-Celebrity-Game',
	},
	{
		id: 11,
		title: 'Next-Todo',
		text: 'A full-stack Todo app with OAuth authentication, TanStack Query, and Neon PostgreSQL database.',
		imagePath: '/todo-next.png',
		githubUrl: 'https://github.com/Pmacdon15/todo-next',
		url: 'https://www.next-todo.patmac.ca/',
	},
	{
		id: 12,
		title: 'Todo',
		text: 'A todo app with JWT authentication, CRUD operations, and MySQL database.',
		imagePath: '/Todo.png',
		githubUrl: 'https://github.com/Pmacdon15/todo',
	},
	{
		id: 13,
		title: 'Shenanigans Mac-Server-Face',
		text: 'A server for HID attacks, executing PowerShell and Bash scripts on target systems.',
		imagePath: '/Shenanigans.jpeg',
		githubUrl: 'https://github.com/Pmacdon15/MacServerFace',
	},
	{
		id: 14,
		title: 'Next Phisher',
		text: 'A Next.js phishing framework with decoy website and customizable phishing page.',
		imagePath: '/Shenanigans.jpeg',
		githubUrl: 'https://github.com/Pmacdon15/nextphisher',
	},
]
