export const projects = [
	{
		id: 1,
		title: 'Landscape Friend',
		text: 'A SaaS platform for landscapers and lawn care businesses to manage services, send emails, and invoices.',
		imagePath: '/landscapefriend.png',
		url: 'https://landscapefriend.com',
		githubUrl: 'https://github.com/Pmacdon15/landscape-friend',
	},
	{
		id: 2,
		title: 'Pardons Are Us',
		text: 'Helping Canadians achieve record suspensions',
		imagePath: '/pardonsareus.png',
		url: 'https://pardonsareus.ca',
		githubUrl: 'https://github.com/Pmacdon15/pardons',
	},
	{
		id: 3,
		title: 'CLock Out',
		text: 'A time tracking app with secure authentication, organization management, and visual analytics.',
		imagePath: '/clockout.png',
		githubUrl: 'https://github.com/Pmacdon15/clock-out',
		url: 'https://clockout.patmac.ca',
	},
	{
		id: 4,
		title: "Pat's Blogs",
		text: 'A modern blog site with image, code, and text upload, and Neon database storage.',
		imagePath: '/blogs.png',
		githubUrl: 'https://github.com/Pmacdon15/blog',
		url: 'https://blog.patmac.ca/',
	},
	{
		id: 5,
		title: 'Days Since Last Vs Code Fork',
		text: 'Kinda of a joke about how long we can go with out a VS Code fork',
		imagePath: '/dayssince.png',
		githubUrl: 'https://github.com/Pmacdon15/days-since',
		url: 'https://dayssincelastvscodefork.patmac.ca/',
	},
	{
		id: 6,
		title: 'Your Next Site',
		text: 'Need a website? We can help visit yournextsite.ca and send us a message.',
		imagePath: '/yournextsite.png',
		githubUrl: 'https://github.com/Your-Next-Site/yournextsite.ca',
		url: 'https://yournextsite.ca',
	},
	{
		id: 7,
		title: 'PolyMuse Wordpress WooCommerce Plugin',
		text: 'A custom plugin for Polymuse, enabling 3D model display and AR views on mobile devices.',
		imagePath: '/polymuse.jpeg',
		githubUrl: 'https://github.com/Dream-Team-Seven/polymuse-woocommerce',
	},
	{
		id: 8,
		title: "Pat's Pre-Trips",
		text: 'A pre-trip inspection app with authentication, current and past trips, and defect listing.',
		imagePath: '/patspretrips1.png',
		githubUrl: 'https://github.com/Pmacdon15/pats-pretrips',
		url: 'https://patspretrips.ca/',
	},
	{
		id: 9,
		title: 'Pat GPT',
		text: 'An Android chat and image generator app using GPT-3 Turbo and DALL-E-3 models.',
		imagePath: '/PatGPT.png',
		githubUrl: 'https://github.com/Pmacdon15/PatGPT',
	},
	{
		id: 10,
		title: 'Free QR Code Generator',
		text: 'A modern QR code generator with URL formatting and PNG download.',
		imagePath: '/qrcode.png',
		githubUrl: 'https://github.com/Pmacdon15/free-qrcode',
		url: 'https://freeqrcode.patmac.ca/',
	},
	{
		id: 11,
		title: 'Nasa Media',
		text: 'A place to see cool things from space.',
		imagePath: '/nasamedia.png',
		url: 'https://nasamedia.patmac.ca/',
		githubUrl: 'https://github.com/Pmacdon15/nasa-images',
	},
	{
		id: 12,
		title: 'Pat Chat 2.0',
		text: 'A real-time chat application built with TypeScript, Next.js, and Ably.',
		imagePath: '/PatChat2.png',
		githubUrl: 'https://github.com/Pmacdon15/patchat2.0',
		url: 'https://www.patchat.ca',
	},
	{
		id: 13,
		title: 'Guess The Celebrity Game',
		text: 'An Android game developed in Java, focusing on saving and restoring state.',
		imagePath: '/GuessingGame.png',
		githubUrl: 'https://github.com/Pmacdon15/Guess-The-Celebrity-Game',
	},
	{
		id: 14,
		title: 'Github Status',
		text: 'View a Github users stats or link a stats card to your Github README.md',
		imagePath: '/GithubStats.png',
		githubUrl: 'https://github.com/Pmacdon15/github-stats.git',
		url: 'https://gh-stats.patmac.ca/',
	},
	{
		id: 15,
		title: 'Next-Todo',
		text: 'A full-stack Todo app with OAuth authentication, TanStack Query, and Neon PostgreSQL database.',
		imagePath: '/todo-next.png',
		githubUrl: 'https://github.com/Pmacdon15/todo-next',
		url: 'https://www.next-todo.patmac.ca/',
	},
	{
		id: 16,
		title: 'Shenanigans Mac-Server-Face',
		text: 'A server for HID attacks, executing PowerShell and Bash scripts on target systems.',
		imagePath: '/Shenanigans.jpeg',
		githubUrl: 'https://github.com/Pmacdon15/MacServerFace',
	},
	{
		id: 17,
		title: 'Next Phisher',
		text: 'A Next.js phishing framework with decoy website and customizable phishing page.',
		imagePath: '/Shenanigans.jpeg',
		githubUrl: 'https://github.com/Pmacdon15/nextphisher',
	},
]
